services:
  postgres:
    image: postgres:17
    container_name: fintrack-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintrack_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
    container_name: fintrack-api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  postgres_data: